---
- hosts: localhost
  gather_facts: no
  vars:
    engine_url: "https://rhvm.lab.example.com/ovirt-engine/api"
    engine_user: "admin@internal"
    engine_password: "redhat"
    vm_name: CREDITO
    txt_numbers_vms: 1
    txt_ips_addrs: "192.168.200.100"
    dd_prefix: 24
    txt_defgw: "192.168.200.1"

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url | default(lookup('env','OVIRT_URL')) | default(omit) }}"
        hostname: "{{ engine_fqdn | default(lookup('env','OVIRT_HOSTNAME')) | default(omit) }}"
        username: "{{ engine_user | default(lookup('env','OVIRT_USERNAME')) | default(omit) }}"
        password: "{{ engine_password | default(lookup('env','OVIRT_PASSWORD')) | default(omit) }}"
        ca_file: "{{ engine_cafile | default(lookup('env','OVIRT_CAFILE')) | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      when: ovirt_auth is undefined or not ovirt_auth

    - name: Create VMs
      block:
        - name: Execute script to get Hypervisor with more Free Mem.
          local_action: script /tmp/get_info_api.bash

        - name: Fill Hyervisor var with result script execution.
          include_vars: /tmp/best_hypervisor.yml

        - name: Fill Storage Domain var with result script execution.
          include_vars: /tmp/best_storage.yml

        - name: Execute ansible creation
          ovirt_vm:
            comment: "Comentario"
            auth: "{{ ovirt_auth }}"
            cluster: CL_CLIENT
            host: "{{ rhvhost }}"
            clone: true
            storage_domain: "{{ storage_domain }}"
            template: "rhel_7.6_template"
            name: "{{ vm_name }}0{{ item }}"
            state: running
            memory: "1GiB"
            cpu_cores: "1"
            high_availability: true
            type: server
            nics:
              - name: nic1
                profile_name: "vNetAdmin"
            cloud_init:
              host_name: "{{ vm_name }}0{{ item }}"
              user_name: root
              root_password: "redhat"
              custom_script: |
                runcmd:
                  - echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
                  - echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
                  - nmcli --fields UUID con show | awk '!/UUID/ {print}' | while read line; do nmcli con delete uuid $line; done
                  - nmcli con add type ethernet con-name eth0 ifname eth0
                  - nmcli con mod eth0
                    connection.autoconnect yes
                    ipv6.method ignore
                    ipv4.method manual
                    ipv4.addresses {{ txt_ips_addrs.split(',')[item - 1] }}/{{ dd_prefix }}
                    ipv4.gateway {{ txt_defgw }}
                    ipv4.dns-search "example.com lab.example.com"
                  - nmcli con up eth0
                  - systemctl restart systemd-sysctl
                  - yum -y remove cloud-init
                coreos:
                  units:
                  - name: systemd-sysctl.service
                    command: restart
            wait: true
      with_items:
        - "{{ range(1, txt_numbers_vms + 1) | list }}"

      always:
        - name: Cleanup RHV auth token
          ovirt_auth:
            ovirt_auth: "{{ ovirt_auth }}"
            state: absent
